export const COMPANY_STATUS = {
  NOT_ACCEPT : 0, // chưa xác minh
  ACCEPT: 1, // chấp nhận duyệt công ty
  NOT_ACCEPT: 2 // từ chối duyệt công ty
}

export const DECETRALIZATION = {
  VIEW_DASHBOARD : 'VIEW_DASHBOARD',
  VIEW_STATIONS : 'VIEW_STATIONS',
  VIEW_STATIONS_USERS : 'VIEW_STATIONS_USERS',
  VIEW_STATIONS_STAFFS : 'VIEW_STATIONS_STAFFS',
  VIEW_STATIONS_VEHICLES : 'VIEW_STATIONS_VEHICLES',
  VIEW_STATIONS_DOCUMENT : 'VIEW_STATIONS_DOCUMENT',
  VIEW_STATIONS_SCHEDULE : 'VIEW_STATIONS_SCHEDULE',
  VIEW_STATIONS_REPORT : 'VIEW_STATIONS_REPORT',
  VIEW_STATIONS_DEVICES : 'VIEW_STATIONS_DEVICES',
  VIEW_APP_USERS : 'VIEW_APP_USERS',
  VIEW_STAFFS : 'VIEW_STAFFS',
  VIEW_CHAT : 'VIEW_CHAT',
  VIEW_NOTIFICATION : 'VIEW_NOTIFICATION',
  VIEW_DOCUMENTS : 'VIEW_DOCUMENTS',
  VIEW_NEWS : 'VIEW_NEWS',
  VIEW_PAYMENTS : 'VIEW_PAYMENTS',
  VIEW_INTEGRATIONS : 'VIEW_INTEGRATIONS',
  VIEW_SYSTEM_CONFIGURATIONS : 'VIEW_SYSTEM_CONFIGURATIONS'
}